import { createContext, ReactNode, useCallback, useContext, useEffect, useMemo, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useAuth } from '@hooks/useSupabaseAuth';

export const languageDefinitions = [
  { code: 'en', shortLabel: 'EN', flag: '🇬🇧', labelKey: 'languageEnglish' },
  { code: 'de', shortLabel: 'DE', flag: '🇩🇪', labelKey: 'languageGerman' },
] as const;
export type LanguageCode = (typeof languageDefinitions)[number]['code'];

type TranslationVars = Record<string, string | number>;

const translations = {
  en: {
    languageLabel: 'Language',
    languageEnglish: 'English',
    languageGerman: 'Deutsch',
    upcomingShifts: 'Shifts',
    enableLocationHint: 'Enable location to see nearby shifts',
    locationCoordinates: 'Location: {coords}',
    locationUnknown: 'Location data unavailable',
    listView: 'List view',
    calendarView: 'Calendar view',
    shiftOverview: 'Shift overview',
    shiftPlanningSubtitle: 'Shift planning & updates',
    stageLabel: 'Stage',
    countdownLabel: 'Countdown',
    timingSnapshot: 'Timing snapshot',
    dayLabel: 'Day',
    prepLabel: 'Prep',
    focusPointsLabel: 'Focus points',
    whereLabel: "Where you'll be",
    openInMaps: 'Open in maps',
    whatYoullDoLabel: 'What you’ll do',
    noDescription:
      'No description was provided. Touch base with operations if you need the rundown.',
    needAHand: 'Need a hand?',
    reachOutCopy:
      'Reach out to {contact} if anything changes or if you need a quick refresher before clocking in.',
    callLabel: 'Call',
    emailLabel: 'Email',
    phoneLabel: 'Phone',
    addressLabel: 'Address',
    contactInformation: 'Contact information',
    notProvided: 'Not provided',
    cta: 'Clock in with QR',
    arriveTip: 'Arrive 10 minutes early',
    badgeTip: 'Wear badge and mask',
    reviewTip: 'Review guest list',
    headToLocation: 'Head to location',
    prepGear: 'Prep gear',
    liveNow: 'Live now',
    startingSoon: 'Starting soon',
    upcoming: 'Upcoming',
    heroStatsStart: 'Start',
    heroStatsEnd: 'End',
    heroStatsDuration: 'Duration',
    shiftSyncFailedTitle: 'Shift sync failed',
    shiftSyncFailedMessage:
      'We could not load your assignments right now. Retry or contact support if the issue persists.',
    retrySync: 'Retry sync',
    listEmptyTitle: 'No shifts scheduled for {month}.',
    listEmptySubtitle: 'Check back soon or refresh to see new assignments that match your availability.',
    refreshShifts: 'Refresh shifts',
    shiftWindowLabel: 'Shift window',
    shiftStartLabel: 'Starts',
    shiftEndLabel: 'Ends',
    shiftDuration: 'Duration',
    locationTbd: 'Location TBD',
    beOnTime: 'Be on time',
    confirmed: 'Confirmed',
    statusScheduled: 'Scheduled',
    statusInProgress: 'In progress',
    statusCompleted: 'Completed',
    statusBlocked: 'Blocked',
    statusScheduledDescription: 'This shift is confirmed and ready for you to accept.',
    statusInProgressDescription:
      'You are currently on the clock—wrap up the essentials and keep the momentum.',
    statusCompletedDescription: 'Nice work! This shift is marked as completed.',
    statusBlockedDescription: 'This assignment needs attention before you can start.',
    confirmShift: 'Confirm shift',
    phasePast: 'Past shift',
    phaseLive: 'Live now',
    phaseUpcoming: 'Upcoming',
    profileGreeting: 'Hello, {name}!',
    profileSettingsSync: 'Profile settings are synced across web and Expo.',
    memberSince: 'Member since {date}',
    memberSinceLabel: 'Member since',
    providerLabel: 'Provider',
    emailVerifiedLabel: 'Email verified',
    yes: 'Yes',
    pending: 'Pending',
    no: 'No',
    security: 'Security',
    accountSnapshot: 'Account snapshot',
    preferencesTitle: 'Preferences',
    appearance: 'Appearance',
    lightMode: 'Light mode',
    darkMode: 'Dark mode',
    signOut: 'Sign out',
    switchAccount: 'Need to switch accounts? Log in again',
    keepSignedIn: 'Keep me signed in',
    statusActive: 'Active',
    accountSnapshot: 'Account snapshot',
    preferencesTitle: 'Preferences',
    calendarMenuTitle: 'Calendar',
    calendarMenuOpen: 'Open calendar',
    calendarMenuSync: 'Sync shifts',
    calendarMenuImportGoogle: 'Import from Google Calendar',
    calendarMenuImportOutlook: 'Import from Outlook',
    calendarMenuSelectionPrompt: 'Select one or more calendars to highlight.',
    calendarMenuSelectionCount: '{count} calendars selected',
    calendarMenuImported: 'Imported calendars',
    calendarLegendTitle: 'Legend',
    calendarLegendImported: 'Imported calendars',
    calendarLegendPink: 'External holidays/imported feed',
    calendarLegendShiftGroup: 'Imported from other calendars',
    calendarLegendTimeGroup: 'My Shifts',
    calendarLegendMorning: 'Morning shift',
    calendarLegendEvening: 'Evening shift',
    calendarLegendNight: 'Night shift',
    calendarLegendImportedDesc: 'Dot markers represent events coming from your external calendars.',
    calendarLegendPinkDesc: 'Additional imported markers (holidays, team calendars).',
    calendarLegendMorningDesc: 'Shift that starts in the morning window.',
    calendarLegendEveningDesc: 'Shift that starts in the afternoon/evening.',
    calendarLegendNightDesc: 'Shift that begins at night.',
    calendarDetailTitle: 'Day details',
    calendarDetailShiftsTitle: 'Shift assignments',
    calendarDetailImportedTitle: 'Imported events',
    calendarDetailNoEvents: 'No shifts scheduled for this day.',
    calendarDetailNoImports: 'No imported events on this day.',
    calendarDetailLocationUnknown: 'Location TBD',
    calendarDetailImportedUntitled: 'Untitled event',
    calendarDetailImportedCalendarFallback: 'External calendar',
    calendarDetailTimeLabel: 'Time',
    reportsTitle: 'Reports',
    reportGeneratePdf: 'Export monthly performance report',
    reportDownloadSummary: 'Download quick shift insights',
    reportGeneratedTitle: 'Report ready',
    reportGeneratedBody: 'The report has been generated; check your downloads.',
    reportMonthlyDescribe: 'Get a polished monthly view of totals, upcoming windows, and notes in one PDF.',
    reportSummaryDescribe: 'Grab an instant overview of your most recent shifts, statuses, and locations.',
    reportSummaryShiftsLabel: 'Shifts included',
    reportSummaryHoursLabel: 'Total hours',
    reportPreviewHint: 'Tap a shift to include or exclude it from the final PDF.',
    reportPreviewSettingsTitle: 'Settings',
    reportPreviewFiltersTitle: 'Filters',
    reportPreviewIncludedBadge: 'Included in export',
    reportPreviewExcludedBadge: 'Excluded from export',
    reportPreviewTitleLabel: 'Report title',
    reportPreviewTitlePlaceholder: 'Enter the title for the PDF',
    reportPreviewDescriptionLabel: 'Report summary',
    reportPreviewDescriptionPlaceholder: 'Describe what this month should highlight',
    reportPreviewNoteLabel: 'Notes for the report',
    reportPreviewNotePlaceholder: 'Optional context for operations',
    reportPreviewThemeDefault: 'Primary gradient',
    reportPreviewThemeSoft: 'Soft gradient',
    reportPreviewInclude: 'Include in report',
    reportPreviewExclude: 'Exclude from report',
    reportCustomizationTitle: 'Customize report metadata',
    reportDownloadedTitle: 'Report downloaded',
    reportDownloadedBody: 'Saved under {path}.',
    reportOptionEmployeeName: 'Employee name',
    reportOptionEmail: 'Email',
    reportOptionPhone: 'Phone number',
    reportOptionObjectName: 'Object name',
    reportOptionAddress: 'Object address',
    reportOptionTotalHours: 'Include total working hours',
    reportOptionShiftLocation: 'Include shift locations',
    reportMetadataTitle: 'Report details',
    reportMetadataEmployee: 'Employee',
    reportMetadataEmail: 'Email',
    reportMetadataPhone: 'Phone',
    reportMetadataTotalHours: 'Total working hours',
    reportMetadataObjectDetails: 'Site details',
    reportMetadataHoursUnit: 'hrs',
    reportMetadataUnknown: 'Not provided',
    reportShiftSummary: '{count} shifts · Starting {start}',
    reportFooter: 'Generated by Employee Portal',
    reportNoShifts: 'No shifts available for the selected period.',
    reportFailedTitle: 'Report failed',
    reportFailedBody: 'Unable to build the PDF right now. Please try again later.',
    reportGenerating: 'Generating report…',
    reportPreviewDownload: 'Download PDF',
    reportPreviewClose: 'Close preview',
    calendarMenuAvailable: 'Available calendars',
    calendarMenuLoading: 'Loading calendars…',
    calendarMenuNoCalendars: 'No calendars found',
    quickActionsTitle: 'Quick actions',
    quickActionsMenuTitle: 'Quick actions',
    quickActionClockIn: 'Clock in',
    quickActionClockInSub: 'Tap to start your next shift',
    quickActionHours: 'Hours',
    quickActionHoursSub: 'Track this week’s logged hours',
    quickActionSupport: 'Support',
    quickActionSupportSub: 'Message operations',
    upcomingShiftListTitle: 'Shift',
    shiftSnapshot: 'Shift snapshot',
    shiftHoursLabel: 'Shift hours',
    nextShift: 'Next shift',
    viewSchedule: 'View schedule',
    noUpcomingShifts: 'No upcoming shifts',
    shiftsTabTitle: 'Shifts',
    loginTitle: 'Employee Portal',
    loginCreateTitle: 'Create your account',
    loginSignInSubtitle: 'Sign in with your company credentials.',
    loginEmailPlaceholder: 'you@company.com',
    loginPasswordPlaceholder: 'Password',
    loginCreateButton: 'Create account',
    loginSignInButton: 'Sign in',
    loginShowPassword: 'Show password',
    loginHidePassword: 'Hide password',
    loginClearEmail: 'Clear email',
    loginAlreadyHaveAccount: 'Already have an account? Sign in',
    loginNeedAccount: 'Need a new account? Sign up',
    continueAsGuestButton: 'Continue as guest',
    continueAsGuestSubtitle: 'Browse roles, perks, and community stories without logging in.',
    guestJobTab: 'Job Offers',
    guestPerksTab: 'Perks',
    guestCommunityTab: 'Community',
    guestHeroTitle: 'Explore Employee Portal',
    guestHeroSubtitle: 'Preview shifts, perks, and behind-the-scenes stories before you sign in.',
    guestJobSectionTitle: 'Featured openings',
    guestJobActionButton: 'See what it’s like',
    guestJobActionTitle: 'Learn more about {jobTitle}',
    guestJobActionBody: 'We’ll share the full application info once you connect with our talent team.',
    guestPerksHeroTitle: 'Benefits at a glance',
    guestPerksHeroSubtitle: 'From wellness stipends to flexible paycheck access, here is what the team enjoys day-to-day.',
    guestPerksSectionTitle: 'Perks line-up',
    guestPerksActionButton: 'Tell me more',
    guestPerksActionTitle: 'Perk highlight: {perkTitle}',
    guestPerksActionBody: 'Great choice! We’ll show you how it works once you create an account or message the team.',
    guestCommunityHeroTitle: 'Meet the crew',
    guestCommunityHeroSubtitle: 'Live events, stories, and open forums keep the vibe transparent. Tap each highlight to feel the energy.',
    guestCommunityStoriesLabel: 'Crew stories',
    guestCommunityUpcomingLabel: 'What’s happening next',
    loginSupportText: 'Need help? Email support',
    loginBackToJobs: 'No credentials? Back to jobs',
    authEmailPasswordRequiredTitle: 'Email and password required',
    authEmailPasswordRequiredBody: 'Please enter both email and password.',
    authInvalidEmailBody: 'Please enter a valid email address.',
    authConfigurationMissingTitle: 'Configuration missing',
    authConfigurationMissingBody: 'Set SUPABASE_URL and SUPABASE_ANON_KEY before logging in.',
    authVerifyEmailTitle: 'Verify your email',
    authVerifyEmailBody: 'We sent a verification link to activate your account.',
    authFailedTitle: 'Authentication failed',
    authUnableSignIn: 'Unable to sign in',
    startupJobsTitle: 'Jobs',
    startupJobsGoToLogin: 'Go to login',
    startupJobsCount: '{count} jobs',
    startupJobsShownCount: '{count} shown',
    startupJobsSearchPlaceholder: 'Search title, location, type, company',
    startupJobsSearchHint: 'Try: location:Berlin type:part-time company:Lidl',
    startupJobsClearSearch: 'Clear search',
    startupJobsLoading: 'Loading startup jobs...',
    startupJobsNoMatches: 'No matching jobs.',
    startupJobsApplyNow: 'Apply now',
    startupJobsOpenLinkFailed: 'Unable to open the job link.',
    startupJobsMissingApiBaseUrl: 'Missing API base URL. Set API_BASE_URL in environment.',
    startupJobsMissingAccessToken: 'Please sign in to load jobs.',
    startupJobsLoadFailed: 'Failed to load startup jobs.',
    requestingCameraPermission: 'Requesting camera permission...',
    cameraPermissionRequired: 'Camera permission is required to scan a QR.',
    grantCameraAccess: 'Grant camera access',
    qrInstructions: 'Point the camera at the QR / barcode provided by your manager.',
    lastScanLabel: 'Last scan',
    scanAnotherBadge: 'Scan another badge',
    qrDetectedTitle: 'QR detected',
    qrDetectedMessage: 'Last scanned code: {code}',
    shiftNotFound: 'Shift not found. Pull to retry.',
    retry: 'Retry',
    back: 'Zurück',
    back: 'Back',
  },
  de: {
    languageLabel: 'Sprache',
    languageEnglish: 'Englisch',
    languageGerman: 'Deutsch',
    upcomingShifts: 'Schichten',
    enableLocationHint: 'Standort freigeben, um Schichten in deiner Nähe zu sehen',
    locationCoordinates: 'Standort: {coords}',
    locationUnknown: 'Standortdaten nicht verfügbar',
    listView: 'Listenansicht',
    calendarView: 'Kalenderansicht',
    shiftOverview: 'Schichtübersicht',
    shiftPlanningSubtitle: 'Schichtplanung & Updates',
    stageLabel: 'Phase',
    countdownLabel: 'Countdown',
    timingSnapshot: 'Zeitübersicht',
    dayLabel: 'Tag',
    prepLabel: 'Vorbereitung',
    focusPointsLabel: 'Wichtige Punkte',
    whereLabel: 'Einsatzort',
    openInMaps: 'In Karten öffnen',
    whatYoullDoLabel: 'Was du tun wirst',
    noDescription:
      'Keine Beschreibung hinterlegt. Kontaktiere das Einsatzteam, wenn du eine kurze Zusammenfassung brauchst.',
    needAHand: 'Brauchst du Hilfe?',
    reachOutCopy:
      'Kontaktiere {contact}, wenn sich etwas ändert oder du vor dem Einchecken noch einmal kurz den Ablauf durchgehen möchtest.',
    callLabel: 'Anruf',
    emailLabel: 'E-Mail',
    phoneLabel: 'Telefon',
    addressLabel: 'Adresse',
    contactInformation: 'Kontaktinformationen',
    notProvided: 'Nicht angegeben',
    cta: 'Mit QR einchecken',
    arriveTip: '10 Minuten vorher da sein',
    badgeTip: 'Badge und Maske tragen',
    reviewTip: 'Gästeliste prüfen',
    headToLocation: 'Zum Einsatzort aufbrechen',
    prepGear: 'Arbeitsmaterialien vorbereiten',
    liveNow: 'Jetzt live',
    startingSoon: 'Startet bald',
    upcoming: 'Kommend',
    heroStatsStart: 'Beginn',
    heroStatsEnd: 'Ende',
    heroStatsDuration: 'Dauer',
    shiftSyncFailedTitle: 'Schicht synchronisierung fehlgeschlagen',
    shiftSyncFailedMessage:
      'Wir konnten deine Einsätze gerade nicht laden. Bitte erneut versuchen oder das Support-Team kontaktieren.',
    retrySync: 'Erneut versuchen',
    listEmptyTitle: 'Für {month} sind aktuell keine Schichten geplant.',
    listEmptySubtitle: 'Sieh später noch einmal nach oder lade neu, um neue Einsätze zu sehen.',
    refreshShifts: 'Schichten aktualisieren',
    shiftWindowLabel: 'Schichtfenster',
    shiftStartLabel: 'Startet',
    shiftEndLabel: 'Endet',
    shiftDuration: 'Dauer',
    locationTbd: 'Ort unbekannt',
    beOnTime: 'Sei pünktlich',
    confirmed: 'Bestätigt',
    statusScheduled: 'Geplant',
    statusInProgress: 'Läuft',
    statusCompleted: 'Abgeschlossen',
    statusBlocked: 'Blockiert',
    statusScheduledDescription: 'Diese Schicht ist bestätigt und bereit zur Annahme.',
    statusInProgressDescription:
      'Du bist aktuell im Einsatz – erledige die wichtigsten Aufgaben und bleib im Flow.',
    statusCompletedDescription: 'Gute Arbeit! Diese Schicht wurde abgeschlossen.',
    statusBlockedDescription: 'Dieser Einsatz braucht noch Aufmerksamkeit, bevor du starten kannst.',
    confirmShift: 'Schicht bestätigen',
    phasePast: 'Vergangene Schicht',
    phaseLive: 'Jetzt live',
    phaseUpcoming: 'Kommend',
    profileGreeting: 'Hallo, {name}!',
    profileSettingsSync: 'Profil-Einstellungen werden zwischen Web und Expo synchronisiert.',
    memberSince: 'Mitglied seit {date}',
    memberSinceLabel: 'Mitglied seit',
    providerLabel: 'Anbieter',
    emailVerifiedLabel: 'E-Mail bestätigt',
    yes: 'Ja',
    pending: 'Ausstehend',
    no: 'Nein',
    security: 'Sicherheit',
    accountSnapshot: 'Kontenübersicht',
    preferencesTitle: 'Einstellungen',
    appearance: 'Erscheinungsbild',
    lightMode: 'Hell-Modus',
    darkMode: 'Dunkel-Modus',
    signOut: 'Abmelden',
    switchAccount: 'Benutzer wechseln? Erneut anmelden',
    keepSignedIn: 'Angemeldet bleiben',
    statusActive: 'Aktiv',
    accountSnapshot: 'Kontenübersicht',
    preferencesTitle: 'Einstellungen',
    calendarMenuTitle: 'Kalender',
    calendarMenuOpen: 'Kalender öffnen',
    calendarMenuSync: 'Schichten synchronisieren',
    calendarMenuImportGoogle: 'Von Google Kalender importieren',
    calendarMenuImportOutlook: 'Von Outlook importieren',
    calendarMenuSelectionPrompt: 'Wähle einen oder mehrere Kalender aus, um sie hervorzuheben.',
    calendarMenuSelectionCount: '{count} Kalender ausgewählt',
    calendarMenuImported: 'Importierte Kalender',
    calendarLegendTitle: 'Legende',
    calendarLegendImported: 'Importierte Kalender',
    calendarLegendPink: 'Externe Feiertage / importierte Quelle',
    calendarLegendShiftGroup: 'Importiert aus anderen Kalendern',
    calendarLegendTimeGroup: 'Meine Schichten',
    calendarLegendMorning: 'Morgenschicht',
    calendarLegendEvening: 'Abendschicht',
    calendarLegendNight: 'Nachtschicht',
    calendarLegendImportedDesc: 'Punkte markieren Termine aus deinen externen Kalendern.',
    calendarLegendPinkDesc: 'Zusätzliche importierte Marker (Feiertage, Team-Kalender).',
    calendarLegendMorningDesc: 'Schicht mit Start am Morgen.',
    calendarLegendEveningDesc: 'Schicht mit Start am Nachmittag/Abend.',
    calendarLegendNightDesc: 'Schicht, die nachts beginnt.',
    calendarDetailTitle: 'Tagesdetails',
    calendarDetailShiftsTitle: 'Schichtzuweisungen',
    calendarDetailImportedTitle: 'Importierte Termine',
    calendarDetailNoEvents: 'Für diesen Tag sind keine Schichten geplant.',
    calendarDetailNoImports: 'Keine importierten Termine an diesem Tag.',
    calendarDetailLocationUnknown: 'Ort unbekannt',
    calendarDetailImportedUntitled: 'Unbenanntes Ereignis',
    calendarDetailImportedCalendarFallback: 'Externer Kalender',
    calendarDetailTimeLabel: 'Uhrzeit',
    reportsTitle: 'Berichte',
    reportGeneratePdf: 'Monatsleistungsbericht exportieren',
    reportDownloadSummary: 'Kurze Schicht-Insights herunterladen',
    reportGeneratedTitle: 'Bericht bereit',
    reportGeneratedBody: 'Der Bericht wurde generiert; überprüfe deinen Download-Ordner.',
    reportMonthlyDescribe: 'Erhalte eine aufbereitete Monatsübersicht mit Summen, bevorstehenden Fenstern und Notizen.',
    reportSummaryDescribe: 'Hol dir sofort einen Überblick über letzte Schichten, Status und Orte.',
    reportSummaryShiftsLabel: 'Eingeschlossene Schichten',
    reportSummaryHoursLabel: 'Gesamtstunden',
    reportPreviewHint: 'Tippe eine Schicht, um sie im Bericht ein- oder auszuschließen.',
    reportPreviewSettingsTitle: 'Einstellungen',
    reportPreviewFiltersTitle: 'Filter',
    reportPreviewIncludedBadge: 'Im Export enthalten',
    reportPreviewExcludedBadge: 'Nicht im Export enthalten',
    reportPreviewTitleLabel: 'Berichtstitel',
    reportPreviewTitlePlaceholder: 'Titel für die PDF eingeben',
    reportPreviewDescriptionLabel: 'Berichtszusammenfassung',
    reportPreviewDescriptionPlaceholder: 'Beschreibe, was diesen Monat hervorheben soll',
    reportPreviewNoteLabel: 'Notizen für den Bericht',
    reportPreviewNotePlaceholder: 'Optionaler Kontext für das Einsatzteam',
    reportPreviewThemeDefault: 'Primärer Verlauf',
    reportPreviewThemeSoft: 'Sanfter Verlauf',
    reportPreviewInclude: 'In Bericht aufnehmen',
    reportPreviewExclude: 'Aus Bericht entfernen',
    reportCustomizationTitle: 'Bericht anpassen',
    reportOptionEmployeeName: 'Mitarbeitername',
    reportOptionEmail: 'E-Mail',
    reportOptionPhone: 'Telefonnummer',
    reportOptionObjectName: 'Objektname',
    reportOptionAddress: 'Objektadresse',
    reportOptionTotalHours: 'Gesamtarbeitsstunden einbeziehen',
    reportOptionShiftLocation: 'Schichtorte einbeziehen',
    reportMetadataTitle: 'Berichtsdetails',
    reportMetadataEmployee: 'Mitarbeiter',
    reportMetadataEmail: 'E-Mail',
    reportMetadataPhone: 'Telefon',
    reportMetadataTotalHours: 'Gesamtarbeitsstunden',
    reportMetadataObjectDetails: 'Standortdetails',
    reportMetadataHoursUnit: 'Std',
    reportMetadataUnknown: 'Nicht verfügbar',
    reportShiftSummary: '{count} Schichten · Beginn {start}',
    reportFooter: 'Erstellt mit Employee Portal',
    reportDownloadedTitle: 'Bericht heruntergeladen',
    reportDownloadedBody: 'Gespeichert unter {path}.',
    reportNoShifts: 'Keine Schichten für den Zeitraum verfügbar.',
    reportFailedTitle: 'Erstellung fehlgeschlagen',
    reportFailedBody: 'Der PDF-Bericht konnte nicht erstellt werden. Bitte versuche es später erneut.',
    reportGenerating: 'Bericht wird erstellt…',
    reportPreviewDownload: 'PDF herunterladen',
    reportPreviewClose: 'Vorschau schließen',
    calendarMenuAvailable: 'Verfügbare Kalender',
    calendarMenuLoading: 'Kalender werden geladen…',
    calendarMenuNoCalendars: 'Keine Kalender gefunden',
    quickActionsTitle: 'Schnellaktionen',
    quickActionsMenuTitle: 'Schnellaktionen',
    quickActionClockIn: 'Einchecken',
    quickActionClockInSub: 'Starte deine nächste Schicht',
    quickActionHours: 'Stunden',
    quickActionHoursSub: 'Diese Woche protokollierte Stunden',
    quickActionSupport: 'Support',
    quickActionSupportSub: 'Kontakt zum Einsatzteam',
    upcomingShiftListTitle: 'Kommende Schichten',
    shiftSnapshot: 'Schichtübersicht',
    shiftHoursLabel: 'Stunden',
    nextShift: 'Nächste Schicht',
    viewSchedule: 'Plan anzeigen',
    noUpcomingShifts: 'Keine kommenden Schichten',
    shiftsTabTitle: 'Schichten',
    loginTitle: 'Employee Portal',
    loginCreateTitle: 'Konto erstellen',
    loginSignInSubtitle: 'Mit deinen Firmen-Zugangsdaten anmelden.',
    loginEmailPlaceholder: 'du@firma.de',
    loginPasswordPlaceholder: 'Passwort',
    loginCreateButton: 'Konto erstellen',
    loginSignInButton: 'Anmelden',
    loginShowPassword: 'Passwort anzeigen',
    loginHidePassword: 'Passwort verbergen',
    loginClearEmail: 'E-Mail löschen',
    loginAlreadyHaveAccount: 'Du hast schon ein Konto? Anmelden',
    loginNeedAccount: 'Noch kein Konto? Registrieren',
    continueAsGuestButton: 'Als Gast fortfahren',
    continueAsGuestSubtitle: 'Durchsuche Jobs, Vorteile und Community-Stories ohne Login.',
    guestJobTab: 'Stellen',
    guestPerksTab: 'Vorteile',
    guestCommunityTab: 'Community',
    guestHeroTitle: 'Employee Portal entdecken',
    guestHeroSubtitle: 'Verschaffe dir einen Eindruck von Schichten, Vorteilen und Teamstories, bevor du dich anmeldest.',
    guestJobSectionTitle: 'Empfohlene Jobs',
    guestJobActionButton: 'Mehr erfahren',
    guestJobActionTitle: 'Mehr Infos zu {jobTitle}',
    guestJobActionBody: 'Nach dem Kontakt mit unserem Team erhältst du den kompletten Bewerbungsfahrplan.',
    guestPerksHeroTitle: 'Vorteile im Überblick',
    guestPerksHeroSubtitle: 'Wellness-Zuschüsse bis Frühzahlen – so arbeiten unsere Teams täglich.',
    guestPerksSectionTitle: 'Highlights',
    guestPerksActionButton: 'Zeig mir mehr',
    guestPerksActionTitle: 'Vorteil im Fokus: {perkTitle}',
    guestPerksActionBody: 'Super Wahl! Sobald du ein Konto hast oder mit dem Team sprichst, gibt’s die Details.',
    guestCommunityHeroTitle: 'Lerne das Team kennen',
    guestCommunityHeroSubtitle: 'Live-Events, Geschichten und offene Räume zeigen, wie wir ticken.',
    guestCommunityStoriesLabel: 'Team-Geschichten',
    guestCommunityUpcomingLabel: 'Was steht an?',
    loginSupportText: 'Brauchen Sie Hilfe? E-Mail an den Support',
    loginBackToJobs: 'Keine Zugangsdaten? Zurück zu Jobs',
    authEmailPasswordRequiredTitle: 'E-Mail und Passwort erforderlich',
    authEmailPasswordRequiredBody: 'Bitte gib sowohl E-Mail als auch Passwort ein.',
    authInvalidEmailBody: 'Bitte gib eine gültige E-Mail-Adresse ein.',
    authConfigurationMissingTitle: 'Konfiguration fehlt',
    authConfigurationMissingBody: 'Setze SUPABASE_URL und SUPABASE_ANON_KEY, bevor du dich einloggst.',
    authVerifyEmailTitle: 'E-Mail bestätigen',
    authVerifyEmailBody: 'Wir haben einen Link zur Aktivierung deines Kontos geschickt.',
    authFailedTitle: 'Authentifizierung fehlgeschlagen',
    authUnableSignIn: 'Anmeldung nicht möglich',
    startupJobsTitle: 'Jobs',
    startupJobsGoToLogin: 'Zum Login',
    startupJobsCount: '{count} Jobs',
    startupJobsShownCount: '{count} angezeigt',
    startupJobsSearchPlaceholder: 'Titel, Ort, Art, Firma suchen',
    startupJobsSearchHint: 'Tipp: location:Berlin type:teilzeit company:Lidl',
    startupJobsClearSearch: 'Suche löschen',
    startupJobsLoading: 'Startup-Jobs werden geladen...',
    startupJobsNoMatches: 'Keine passenden Jobs.',
    startupJobsApplyNow: 'Jetzt bewerben',
    startupJobsOpenLinkFailed: 'Der Job-Link konnte nicht geöffnet werden.',
    startupJobsMissingApiBaseUrl: 'API-Basis-URL fehlt. API_BASE_URL in der Umgebung setzen.',
    startupJobsMissingAccessToken: 'Bitte anmelden, um Jobs zu laden.',
    startupJobsLoadFailed: 'Startup-Jobs konnten nicht geladen werden.',
    requestingCameraPermission: 'Kameraberechtigung wird angefordert...',
    cameraPermissionRequired: 'Kameraberechtigung ist erforderlich, um einen QR zu scannen.',
    grantCameraAccess: 'Kamerazugriff erlauben',
    qrInstructions: 'Richte die Kamera auf den QR-/Barcode aus, den dir deine Leitung gegeben hat.',
    lastScanLabel: 'Zuletzt gescannt',
    scanAnotherBadge: 'Weiteren Badge scannen',
    qrDetectedTitle: 'QR erkannt',
    qrDetectedMessage: 'Zuletzt gescannter Code: {code}',
    shiftNotFound: 'Schicht nicht gefunden. Zieh nach unten, um es erneut zu laden.',
    retry: 'Erneut versuchen',
    back: 'Zurück',
  },
} as const;

const LANGUAGE_STORAGE_KEY_BASE = 'employee-portal-language';
const getLanguageStorageKey = (employeeId?: string | null) =>
  employeeId ? `${LANGUAGE_STORAGE_KEY_BASE}:${employeeId}` : null;
const isValidLanguage = (value: string | null): value is LanguageCode =>
  languageDefinitions.some((definition) => definition.code === value);

type TranslationKey = keyof typeof translations['en'];

type LanguageContextValue = {
  language: LanguageCode;
  setLanguage: (language: LanguageCode) => void;
  t: (key: TranslationKey, vars?: TranslationVars) => string;
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

type Props = {
  children: ReactNode;
};

const interpolate = (value: string, vars?: TranslationVars) => {
  if (!vars) return value;
  return Object.entries(vars).reduce(
    (text, [key, varValue]) => text.replace(`{${key}}`, String(varValue)),
    value
  );
};

export const LanguageProvider = ({ children }: Props) => {
  const { user } = useAuth();
  const storageKey = useMemo(() => getLanguageStorageKey(user?.id), [user?.id]);
  const [language, setLanguageState] = useState<LanguageCode>('en');

  useEffect(() => {
    if (!storageKey) {
      setLanguageState('en');
      return undefined;
    }

    let isMounted = true;
    AsyncStorage.getItem(storageKey)
      .then((stored) => {
        if (!isMounted) return;
        if (isValidLanguage(stored)) {
          setLanguageState(stored);
        } else {
          setLanguageState('en');
        }
      })
      .catch(() => {
        if (isMounted) {
          setLanguageState('en');
        }
      });
    return () => {
      isMounted = false;
    };
  }, [storageKey]);

  const setLanguage = useCallback(
    (newLanguage: LanguageCode) => {
      setLanguageState(newLanguage);
      if (!storageKey) return;
      AsyncStorage.setItem(storageKey, newLanguage).catch(() => {
        /* ignore */
      });
    },
    [storageKey]
  );

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage,
      t: (key, vars) => interpolate(translations[language][key], vars),
    }),
    [language, setLanguage]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export type { TranslationKey };
